name: Ruby

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} | Gemfile ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.2.2"
          - head
        gemfile:
          - Gemfile
          - gemfiles/rails_edge.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
